#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: "__HOSTNAME__" # Pregunta por el hostname durante la instalación
    username: "__USERNAME__" # Pregunta por el nombre de usuario
    password: "$6$rounds=4096$changeme" # Contraseña cifrada; será personalizada

  storage:
    config:
      # Disco principal
      - id: disk0
        type: disk
        ptable: gpt
        path: /dev/nvme0n1
        wipe: superblock
        preserve: false
        name: ''
        grub_device: true

      # Partición EFI
      - id: disk0-part1
        type: partition
        number: 1
        size: 1G
        flag: boot
        device: disk0
        preserve: true
      - id: efi
        type: format
        fstype: vfat
        volume: disk0-part1
        preserve: true
      - id: efi-mount
        type: mount
        path: /boot/efi
        device: efi
        preserve: true

      # Partición raíz "/"
      - id: disk0-part2
        type: partition
        number: 2
        size: 186.3G
        device: disk0
        preserve: false
      - id: root
        type: format
        fstype: ext4
        volume: disk0-part2
      - id: root-mount
        type: mount
        path: /
        device: root

      # Partición swap
      - id: disk0-part3
        type: partition
        number: 3
        size: 5.6G
        device: disk0
        preserve: false
      - id: swap
        type: format
        fstype: swap
        volume: disk0-part3

      # Partición "/home"
      - id: disk0-part4
        type: partition
        number: 4
        size: 139.7G
        device: disk0
        preserve: false
      - id: home
        type: format
        fstype: ext4
        volume: disk0-part4
      - id: home-mount
        type: mount
        path: /home
        device: home

      # Partición "/storage" (preserva datos)
      - id: disk0-part5
        type: partition
        number: 5
        size: 144.3G
        device: disk0
        preserve: true
      - id: storage
        type: mount
        path: /storage
        device: disk0-part5
        preserve: true

  packages:
    - ccze
    - software-properties-common
    - nano
    - git
    - sshpass
    - make
    - progress
    - docker-compose-v2
    - docker.io
    - btop
    - curl
    - apt-transport-https
    - ca-certificates
    - net-tools
    - wget
    - locate

  late-commands:
    # Configuración inicial
    - curtin in-target --target=/target -- bash -c "
        echo 'export LANG=es_ES.UTF-8' >> /etc/bash.bashrc;
        echo 'export EDITOR=nano' >> /etc/bash.bashrc"

    # Configuración de Docker
    - curtin in-target --target=/target -- bash -c "
        usermod -aG docker __USERNAME__;
        chown __USERNAME__ /var/run/docker.sock"

    # Instalación de Postman
    - curtin in-target --target=/target -- bash -c "
        wget https://dl.pstmn.io/download/latest/linux_64 -O postman.tar.gz;
        tar -xzf postman.tar.gz -C /opt;
        ln -s /opt/Postman/Postman /usr/bin/postman;
        rm postman.tar.gz"

    # Anclar iconos al Dock
    - curtin in-target --target=/target -- bash -c "
        gsettings set org.gnome.shell favorite-apps \"['org.gnome.Terminal.desktop', 'code.desktop', 'postman.desktop']\""

    # Instalación de Visual Studio Code
    - curtin in-target --target=/target -- bash -c "
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft.gpg;
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main' > /etc/apt/sources.list.d/vscode.list;
        apt update;
        apt install code -y"

    # Modernizar las fuentes de APT
    - curtin in-target --target=/target -- bash -c "
        apt modernize-sources"

    # Configuración del PPA de OBS Studio para Ubuntu 24.10
    - curtin in-target --target=/target -- bash -c "
        add-apt-repository ppa:obsproject/obs-studio -y;
        sed -i 's/plucky/mantic/g' /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-*.list;
        apt update;
        apt install obs-studio -y"

    # Actualización de base de datos (locate)
    - curtin in-target --target=/target -- updatedb
